### ISSUE TITLE
Connect cloudfront instance via winscp

### ISSUE THREAD

**Issue by asheteh** [ibm-cloud-docs/objectstorage-swift#5]
Hi I have ibmcloufront instance i want to connect using winscpt for data transfer from my local machine to instance please tell me process how can i do that

**Comment by lifemikey** [comment]
Swift Object Storage has gone End of Support.  You can use IBM Cloud Object Storage to transfer files from your local machine.  There are CLIs, and desktop clients that can be used.  I would recommend rclone CLI to go from local machine to IBM Cloud Object Storage.
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-rclone

**Comment by lifemikey** [comment]
This is a Swift Object Storage documentation repo. For any additional questions please open a support ticket.
https://cloud.ibm.com/unifiedsupport/cases/form
