### ISSUE TITLE
How to access  ibm cloudfoundry app instance via putty   

### ISSUE THREAD

**Issue by asheteh** [ibm-cloud-docs/objectstorage-swift#6]
I have one python app on ibm cloudfoundry i want to connect that instance via putty please let me know process how to connect instance using putty

**Comment by lifemikey** [comment]
You can connect to IBM Cloud Object Storage from a Cloud Foundry app using these instructions.
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-cloud-foundry

This is a Swift Object Storage documentation repo.  For any additional questions please open a support ticket.
https://cloud.ibm.com/unifiedsupport/cases/form
